---
version: '2'
services:
  prometheus:
   image: prom/prometheus:latest
   volumes: 
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./alert-rules:/etc/prometheus/alert-rules
    - ./prometheus_data:/prometheus
   command: '-config.file=/etc/prometheus/prometheus.yml'
   ports:
    - '9090:9090'
  
  node-exporter:
    image: prom/node-exporter
    ports:
    - '9100:9100'

  grafana:
    image: grafana/grafana
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
     - ./grafana_data:/var/lib/grafana 
    depends_on:
     - prometheus
    ports:
     - '3000:3000'