---
version: '2'
services:
  prometheus:
   image: prom/prometheus:latest
   volumes: 
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./alert-rules:/etc/prometheus/alert-rules
    - ./prometheus_data:/prometheus
   command:
    - '-config.file=/etc/prometheus/prometheus.yml'
    - '-alertmanager.url=http://alertmanager:9093'
    - '-log.level=debug'
   ports:
    - '9090:9090'

  node-exporter:
   image: prom/node-exporter
   ports:
    - '9100:9100'
   command:
    - '-collector.textfile.directory=/var/lib/node_exporter/textfile_collector/'
   volumes:
    - ./textfile_collector:/var/lib/node_exporter/textfile_collector

  grafana:
    image: grafana/grafana
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
     - ./grafana_data:/var/lib/grafana 
    depends_on:
     - prometheus
    ports:
     - '3000:3000'

  alertmanger:
    image: prom/alertmanager:latest
    volumes:
     - ./alertmanager.yml:/alertmanager.yml
    command:
     - '-config.file=/alertmanager.yml'
    ports:
     - '9093:9093' 

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'