---
global:
  scrape_interval: 5s
  external_labels:
   monitor: 'server-monitor'
rule_files:
 - '/etc/prometheus/alert-rules'

scrape_configs:
 - job_name: 'prometheus'
   static_configs:
    - targets: ['127.0.0.1:9090']

 - job_name: 'node-exporter'
   static_configs:
    - targets: ['node-exporter:9100']

 - job_name: 'cadvisor'
   static_configs:
    - targets: ['cadvisor:8080']

 - job_name: 'blackbox-exporter'
   metrics_path: /probe
   params:
    module: [http_2xx]  # Look for a HTTP 200 response.
   static_configs:
    - targets:
      - prometheus.io   # Target to probe
   relabel_configs:
    - source_labels: [__address__]
      regex: (.*)(:80)?
      target_label: __param_target
      replacement: ${1}
    - source_labels: [__param_target]
      regex: (.*)
      target_label: instance
      replacement: ${1}
    - source_labels: []
      regex: .*
      target_label: __address__
      replacement: blackbox-exporter:9115  # Blackbox exporter.
