---
global:
  scrape_interval: 15s
  external_labels:
   monitor: 'server-monitor'
  rule_files:
   - 'prometheus-rules'

scrape_configs:
 - job_name: 'prometheus'
   scrape_interval: 5s
   static_configs:
    - targets: [':9090']

 - job_name: 'node-exporter'
   static_configs:
    - targets: ['node-exporter:9100']   