---
global:
  scrape_interval: 15s
  external_labels:
   monitor: 'server-monitor'
rule_files:
 - '/etc/prometheus/alert-rules'

scrape_configs:
 - job_name: 'prometheus'
   static_configs:
    - targets: ['127.0.0.1:9090']

 - job_name: 'node-exporter'
   static_configs:
    - targets: ['node-exporter:9100']

 - job_name: 'cadvisor'
   static_configs:
    - targets: ['127.0.0.1:8080']